#!/bin/sh

# Checks that passwd exists and root user exists
# https://www.mankier.com/1/beakerlib#Examples
BEAKERLIB=/usr/local/lib/beakerlib
. /usr/local/lib/beakerlib/beakerlib.sh

rlJournalStart
    rlPhaseStartTest
        rlAssertRpm "setup"
        rlAssertExists "/etc/passwd"
        rlAssertGrep "root" "/etc/passwd"
    rlPhaseEnd
rlJournalEnd
